FROM node:13-alpine

# ARG REACT_APP_API_URL
# ENV REACT_APP_API_URL=$REACT_APP_API_URL

ARG CHOKIDAR_USEPOLLING=true
ENV CHOKIDAR_USEPOLLING=$CHOKIDAR_USEPOLLING

ARG COMPOSE_CONVERT_WINDOWS_PATHS=1
ENV COMPOSE_CONVERT_WINDOWS_PATHS=$COMPOSE_CONVERT_WINDOWS_PATHS

WORKDIR /var/www/front

COPY package*.json ./

RUN npm install

COPY . .

ENV PORT=3000

CMD ["npm", "start"]